### ISSUE TITLE
Doesn't work in Sketch 3.5.1

### ISSUE THREAD

**Issue by theposch** [lewishowles/sketch-bound-with-box#1]
Plugin doesn't seem to work in latest Sketch Version :(

**Comment by lewishowles** [comment]
Did you find out what was happening here? I had some weirdness myself where it seems the method of determining the co-ordinates of the selection had changed (so the box appeared at some random location), but it seems OK now.

Perhaps they fixed something in a recent update!

**Comment by theposch** [comment]
I just forgot to have an artboard around my layers.

**Comment by theposch** [comment]
Would be great if the Plugin would constrain the size of the Bounding box to be always square.
For example, if I have an icons that's 16x16, i always get a bound that's 24x24 with a 4px padding.
But if I have an icon that's 16x12 for example, I still would like to get a square bound box.

**Comment by lewishowles** [comment]
Yeah that caught me out once. I can't think of a time I'd want to have a real document without an artboard but if it's an issue let me know.

**Comment by theposch** [comment]
Not an issue at all.

**Comment by lewishowles** [comment]
Hmmm, I'd have to have 'square' as a non-default option but I could probably do that. I could probably make it based on the widest of the two values (in that case the width of 16).

I'll have a think.

**Comment by lewishowles** [comment]
There you go! It seems to work for me with rudimentary testing, hope it helps.

**Comment by theposch** [comment]
Oh this is awesome! Thanks a ton!
