### ISSUE TITLE
Nothing happens for layers in group

### ISSUE THREAD

**Issue by vibin** [lewishowles/sketch-bound-with-box#3]
Hi, I'm not sure if I'm doing this wrong, or if the plugin is buggy. See this screencast https://drive.google.com/open?id=0B6XmqPKEJKIeRHdOZ0ZhakNicjQ

I selected all the layers of a group and ran the plugin, tried with both Move Contents and Move Box options, but nothing happens.

**Comment by lewishowles** [comment]
What version of Sketch and the plugin do you have?

**Comment by vibin** [comment]
Sketch v42 (36781) and Bound with Box v1.4

**Comment by lewishowles** [comment]
I've just pushed out version 1.5 which fixes an error in the latest version of sketch, which removed one of the functions being used.

It will now also allow you to work in a group or page, without needing an artboard.

Let me know if that works for you.

**Comment by vibin** [comment]
Thanks for the quick fix! Works great now. Also, I just realized you can provide negative padding 😄. You should mention this in the README.
